name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  GODOT_VERSION: 4.3
  EXPORT_NAME: EchoBound_Riftborn

jobs:
  export-android:
    name: Android Export
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.3

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Move export templates into place
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable

      - name: Export Android APK
        run: |
          mkdir -v -p build/android
          godot --headless --verbose --export-debug "Android" ./build/android/${EXPORT_NAME}.apk

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: EchoBound_Riftborn-apk
          path: build/android
